version: '3.6'
services:
  mongo:
    image: mongo:4.4.3-bionic
#    volumes:
#      - ./data:/data
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: employees
    command: "mongod --auth"
